apiVersion: tunnel.jprq.io/v1alpha1
kind: JprqTunnel
metadata:
  labels:
    app.kubernetes.io/name: jprq-bek
    app.kubernetes.io/managed-by: kustomize
  name: jprqtunnel-sample
spec:
  # TODO(user): Add fields here
